#!/usr/bin/env bash
#
# Build a .deb from an already-compiled binary set.
#
# Run on a Debian or Ubuntu host with dpkg-deb available:
#
#   make release            # produces dist/
#   deploy/debian/build-deb.sh v0.3.0 amd64
#
# The result is what `apt install` consumes, and it is the recommended way to
# install PrivateDNS: a package manager gives an operator upgrade, rollback,
# integrity checking and clean removal without any of it being reimplemented in
# a shell script.

set -euo pipefail

VERSION="${1:-}"
ARCH="${2:-amd64}"

[[ -n "$VERSION" ]] || { echo "usage: $0 <version> [amd64|arm64]" >&2; exit 1; }

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DIST="${ROOT}/dist"
STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT

command -v dpkg-deb >/dev/null 2>&1 || {
  echo "dpkg-deb is required; run this on a Debian or Ubuntu host" >&2
  exit 1
}

# Version strings in Debian may not carry a leading v.
DEB_VERSION="${VERSION#v}"

echo "==> Staging privatedns ${DEB_VERSION} (${ARCH})"

install -d "${STAGE}/DEBIAN"
install -d "${STAGE}/usr/local/bin"
install -d "${STAGE}/lib/systemd/system"
install -d "${STAGE}/etc/private-dns"
install -d "${STAGE}/usr/share/doc/privatedns"

for comp in resolver backend portal admin; do
  src="${DIST}/privatedns-${comp}-linux-${ARCH}"
  [[ -f "$src" ]] || { echo "missing ${src}; run 'make release' first" >&2; exit 1; }
  install -m 0755 "$src" "${STAGE}/usr/local/bin/privatedns-${comp}"
done

install -m 0755 "${ROOT}/scripts/private-dns"   "${STAGE}/usr/local/bin/private-dns"
install -m 0755 "${ROOT}/scripts/update.sh"     "${STAGE}/usr/local/bin/update"
install -m 0755 "${ROOT}/scripts/uninstall.sh"  "${STAGE}/usr/local/bin/uninstall"
install -m 0755 "${ROOT}/deploy/scripts/issue-cert.sh" \
                "${STAGE}/usr/local/bin/privatedns-issue-cert"
install -m 0755 "${ROOT}/deploy/scripts/fetch-blocklists.sh" \
                "${STAGE}/usr/local/bin/privatedns-fetch-blocklists"

install -m 0644 "${ROOT}"/deploy/systemd/privatedns-*.service "${STAGE}/lib/systemd/system/"

# Examples only. The live configuration is generated by postinst on a first
# install and never touched afterwards.
install -m 0644 "${ROOT}"/configs/*.example.* "${STAGE}/etc/private-dns/"

install -m 0644 "${ROOT}/README.md"  "${STAGE}/usr/share/doc/privatedns/"
install -m 0644 "${ROOT}/LICENSE"    "${STAGE}/usr/share/doc/privatedns/copyright"

sed -e "s/VERSION_PLACEHOLDER/${DEB_VERSION}/" \
    -e "s/ARCH_PLACEHOLDER/${ARCH}/" \
    "${ROOT}/deploy/debian/control" > "${STAGE}/DEBIAN/control"

for script in postinst prerm postrm; do
  install -m 0755 "${ROOT}/deploy/debian/${script}" "${STAGE}/DEBIAN/${script}"
done

# Marking the generated config as a conffile would make dpkg prompt about
# local changes on every upgrade. It is generated rather than shipped, so it
# is deliberately not listed here.
cat > "${STAGE}/DEBIAN/conffiles" <<'EOF'
EOF

mkdir -p "$DIST"
OUT="${DIST}/privatedns_${DEB_VERSION}_${ARCH}.deb"

dpkg-deb --build --root-owner-group "$STAGE" "$OUT"

echo "==> Built ${OUT}"
dpkg-deb --info "$OUT" | sed 's/^/    /'
echo
echo "Install with:"
echo "    sudo apt install ./$(basename "$OUT")"
